---
id: theme-material
name: theme-material
full: Horde Material UI Theme
description: >-
  This theme intends to get the Horde UI as close as possible to Material UI standards.
list: ~
type: horde-theme
homepage: https://www.horde.org/apps/horde
authors:
  -
    name: Ralf Lang
    user: rlang
    email: lang@b1-systems.de
    active: true
    role: lead
version:
  release: 1.0.0
  api: 1.0.0
state:
  release: stable
  api: stable
license:
  identifier: LGPL-2
  uri: http://www.horde.org/licenses/lgpl
dependencies:
  required:
    php: ^7 || ^8
    composer:
      horde/horde: '*'
